### ISSUE TITLE
麻烦更新下项目

### ISSUE THREAD

**Issue by kice** [igordonshaw/inote#1]
很多地方需要更新，不然编译都不用过。

如果已经弃坑了，麻烦标注下。

**Comment by jiuxuanzhi** [comment]
你好，我当时使用的是Go 1.4, Beego 1.5, 我已经基本上没有碰过Go代码了，这个博客也是当时学习Beego时写的，如果你对Go和Beego感兴趣建议去Beego官网跟着开发文档学习，这个博客的代码可以作为一些辅助的参考。
